# Generated by Django 5.2 on 2026-02-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("training", "Training"),
                            ("match", "Match"),
                            ("meeting", "Meeting"),
                            ("other", "Other"),
                        ],
                        default="training",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("time", models.TimeField()),
                ("venue", models.CharField(max_length=100)),
                (
                    "jersey_color",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["date", "time"],
                "indexes": [
                    models.Index(fields=["date"], name="idx_event_date"),
                    models.Index(fields=["event_type"], name="idx_event_type"),
                ],
            },
        ),
    ]
