# Generated by Django 5.2 on 2026-02-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_image",
                    models.URLField(blank=True, default="", max_length=500),
                ),
                (
                    "player_image_public_id",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "parent_guardian_name",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("parent_contact_address", models.TextField(blank=True, default="")),
                (
                    "parent_telephone",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                (
                    "relationship_to_student",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("parent_hopes", models.TextField(blank=True, default="")),
                ("surname", models.CharField(db_index=True, max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "other_name",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("contact_address", models.TextField(blank=True, default="")),
                (
                    "state_of_origin",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("lga", models.CharField(blank=True, default="", max_length=100)),
                (
                    "nationality",
                    models.CharField(blank=True, default="Nigerian", max_length=50),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("telephone", models.CharField(blank=True, default="", max_length=20)),
                ("gender", models.CharField(blank=True, default="", max_length=20)),
                ("weight", models.CharField(blank=True, default="", max_length=10)),
                ("height", models.CharField(blank=True, default="", max_length=10)),
                (
                    "academic_status",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                (
                    "previous_team",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "reason_for_leaving",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "soccer_position",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=50
                    ),
                ),
                ("player_hopes", models.TextField(blank=True, default="")),
                ("weaknesses", models.JSONField(blank=True, default=list)),
                (
                    "last_treated_sickness",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "blood_group",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("genotype", models.CharField(blank=True, default="", max_length=10)),
                ("any_medical_problem", models.BooleanField(default=False)),
                ("medical_problem_details", models.TextField(blank=True, default="")),
                ("currently_on_medication", models.BooleanField(default=False)),
                (
                    "admission_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("admitted", "Admitted"),
                            ("not_admitted", "Not Admitted"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("team", models.CharField(blank=True, default="BEFA", max_length=100)),
                ("goals", models.IntegerField(default=0)),
                ("assists", models.IntegerField(default=0)),
                ("matches", models.IntegerField(default=0)),
                ("rating", models.FloatField(blank=True, null=True)),
                ("saves", models.IntegerField(blank=True, null=True)),
                ("clean_sheets", models.IntegerField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, default="")),
                ("achievements", models.JSONField(blank=True, null=True)),
                ("is_player_of_the_month", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["surname"], name="idx_player_surname"),
                    models.Index(
                        fields=["soccer_position"], name="idx_player_position"
                    ),
                    models.Index(
                        fields=["admission_status"], name="idx_player_admission"
                    ),
                    models.Index(fields=["-created_at"], name="idx_player_created"),
                    models.Index(
                        fields=["is_player_of_the_month"], name="idx_player_potm"
                    ),
                ],
            },
        ),
    ]
